version: "3.9"
services:
  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=accsess_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "9000:9000"
      - "9090:9090"
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set ui-trade http://minio:9000 root password;
      until mc ls ui-trade; do echo '...waiting...' && sleep 5; done;
      mc mb --ignore-existing ui-trade/ui-trade-private;
      mc mb --ignore-existing ui-trade/ui-trade-public;
      mc mb --ignore-existing ui-trade/ui-trade-preview;
      mc anonymous set download ui-trade/ui-trade-public;
      mc anonymous set private ui-trade/ui-trade-private;
      mc anonymous set download ui-trade/ui-trade-preview;
      "

volumes:
  minio:
